name: Notifications on Pull Request
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Send pull request notifications
        run: |
          GITHUB_REPO_URL="https://github.com/${{ github.repository }}/"
          GITHUB_COMMIT_URL="${GITHUB_REPO_URL}commit/"
          BOT_TOKEN="5736753829:AAE88n5HWh7xWQwzvGG9IgitnFV5xZlvTag"
          WEBHOOK_URL="https://api.telegram.org/bot{$BOT_TOKEN}/sendMessage"
          CHAT_ID="-618920347"
          REPO_NAME="${{ github.event.repository.name }}"
          GITHUB_BRANCH_COMMITS_URL="${GITHUB_REPO_URL}commits/${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}"
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          TIMEZONE_SEVENTH=$(date +%H)
          AUTHOR=${{ github.event.pull_request.user.login }}
          TEXT="A new pull request [#${{ github.event.number }}](${{ github.event.pull_request.html_url }}) has been created by ${AUTHOR} on branch [${GIT_BRANCH}](${GITHUB_BRANCH_COMMITS_URL})"
          SLACK_HEADER="[@Tâm](tg://user?id=2053824848) [${REPO_NAME}](${GITHUB_REPO_URL})\n"
          TEXTS=${SLACK_HEADER}${TEXT}
          MESSAGES=$(echo '{"chat_id":"'"${CHAT_ID}"'","text":"'"${TEXTS}"'", "parse_mode" : "markdown"}')
          echo "${MESSAGES}"
          echo "$TIMEZONE_SEVENTH"
          if [ ${TIMEZONE_SEVENTH#0} -gt 23 ] || [ ${TIMEZONE_SEVENTH#0} -lt 16 ]
          then
          curl -X POST -H 'Content-type: application/json' --data "${MESSAGES}" ${WEBHOOK_URL}
          fi
        continue-on-error: true